version: '3.8'
services:
  container1:
    image: ubuntu
    volumes:
      - mydata:/shared
    networks:
      - mynetwork

  container2:
    image: ubuntu
    volumes:
      - mydata:/shared
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mydata:
